---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cte-4-k8s-sc
provisioner: csi.cte.cpl.thalesgroup.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  # Domain name or IP address of the CiperTrust Manager (Required)
  key_manager_addr: 20.113.58.180

  # Name of the CipherTrust Manager K8s Storage Group. (Required)
  k8_storage_group: myapp-storage-group

  # Kubernetes Secret with CM registration token (Required)
  registration_token_secret: cm-reg-token

  # Small registration description to be displayed in the CiperTrust Manager (Optional)
  client_description: "Kubernetes Worker-Nodes"

  # Time in minutes to wait before unregistering from the CiperTrust Manager
  # once all volumes have been unguarded. Parameter must be added as a string
  # integer value. Default "10" minute. (Optional)
  registration_period: "10"
