---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-test-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4
  nfs:
    path: /
    server: 10.0.4.119

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-storage-claim
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi