apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: EKS_SERVICE_FQDN
  namespace: default
spec:
  secretName: EKS_SERVICE_FQDN-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: EKS_SERVICE_FQDN
  dnsNames:
  - EKS_SERVICE_FQDN