apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: eks-app.az.presales.dev
  namespace: default
spec:
  secretName: eks-app.az.presales.dev-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: eks-app.az.presales.dev
  dnsNames:
  - eks-app.az.presales.dev