apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: GKE_SERVICE_FQDN
  namespace: default
spec:
  secretName: GKE_SERVICE_FQDN-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: GKE_SERVICE_FQDN
  dnsNames:
  - GKE_SERVICE_FQDN